### ISSUE TITLE
Store input data in url

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [aviettran/minecraft-anvil-calc#21]
This would be a cool feature because:
- Share link with item
- Reload page without losing data
- Bookmark / store link to look at later

**Comment by aviettran** [comment]
Sorry, I wasn't subscribed to my own repo for some reason.

I'll take a look at this. I had considered doing this in the past, but never got around to it.

**Comment by aviettran** [comment]
Complete in latest release.
