### ISSUE TITLE
Minor corrections & update

### ISSUE THREAD

**Issue by chatcoda** [aviettran/minecraft-anvil-calc#31]
Excellent work, very useful for me!
I noticed that it's not possible to apply Silk Touch to Shears (which should be the case in BE only).
Secondly, the Brush has been released in version 1.20, to which Unbreaking, Mending and Curse of Vanishing can be applied.
Unfortunately, I don't have the skills to update the code myself...

**Comment by aviettran** [comment]
Simple enough. Complete.

**Comment by chatcoda** [comment]
Thanks, but a think you made a mistake in enchantments.json for Brush : Unbreaking, Mending and Curse of Vanishing can be applied, and it looks like you set Unbreaking, Mending, Curse of Vanishing and **Curse of Binding** instead of Mending.

**Comment by aviettran** [comment]
Right you are. Pushing fix now.

**Comment by chatcoda** [comment]
Perfect, thank you very much. If I notice anything else in the future, I'll let you know.

**Comment by chatcoda** [comment]
I took a closer look. It seems that the only 2 missing items are compass and recovery_compass (both vanishing_curse only). Pretty useless...

**Comment by chatcoda** [comment]
Great, but... you've inverted those spinning images ;-)

**Comment by aviettran** [comment]
oh goodness. fixed.
