### ISSUE TITLE
God Armor Support

### ISSUE THREAD

**Issue by zhon12345** [aviettran/minecraft-anvil-calc#46]
Hi there, I love this project as it lets me combine multiple items which most other tools do not support.

It would be even better if there was another option next to the "java edition" checkbox for a "god armour" checkbox which enables multiple protection stacking which can be done in minecraft version 1.14 -1.14.2

Hopefully this is not that hard to implement and keep up the good work!

**Comment by aviettran** [comment]
#48

**Comment by aviettran** [comment]
Let me know if this does what you need.

**Comment by zhon12345** [comment]
Yup, works like a charm! Thanks!
